name: litewriter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  archive: ^3.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/litewriter_logo.jpg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/litewriter_logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21



  intl: ^0.19.0
