name: Litewriter Android CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.32.3'
  JAVA_VERSION: '17'

jobs:
  build_android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Generate launcher icons
        run: flutter pub run flutter_launcher_icons:main

      - name: Generate code (build_runner)
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Decode Keystore File
        if: env.KEY_STORE_FILE_BASE64 != ''
        run: echo "$KEY_STORE_FILE_BASE64" | base64 --decode > android/app/upload-keystore.jks

      - name: Create key.properties for Signing
        if: env.KEY_STORE_FILE_BASE64 != ''
        run: |
          echo "storeFile=upload-keystore.jks" > android/key.properties
          echo "storePassword=$KEY_STORE_PASSWORD" >> android/key.properties
          echo "keyAlias=$KEY_ALIAS" >> android/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/key.properties

      - name: Build Android APK (Release)
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: litewriter-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30
